### PR TITLE
Fixing bug of None true_label

### PR DESCRIPTION
**Pull request by GreenGilad**
In the current version if `true_label` is not passed in VIA's ctor one get the following exception:

> TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_26896/2431515619.py in <module>
      1 v0 = via.VIA(X, knn=k, root_user=root, is_coarse=True, preserve_disconnected=True)
----> 2 v0.run_VIA()
~\anaconda3\envs\ViaEnv\lib\site-packages\pyVIA\core.py in run_VIA(self)
   3494         self.ncomp = self.data.shape[1]
   3495         pop_list = []
-> 3496         for item in set(list(self.true_label)):
   3497             pop_list.append([item, list(self.true_label).count(item)])
   3498         # print("population composition", pop_list)
TypeError: 'NoneType' object is not iterable

This happens because in the `run_VIA` function `self.true_label` is used in line 3615 but is only initialized in line 3618.
In the suggested fix I simply moved the initialization of `self.true_label` to the ctor

### CODE REVIEW

**Comment by GreenGilad** [comment]
The second commit contains multiple changes of the following types:

- the following:
  ```
    if visual == False:
        data = self.data
    else:
        data = data_visual
  ```
  changed to :
  ```
  data = data_visual if visual else self.data
  ```

- `if too_big == False` to `if not too_big`
- getting array's dimensions. Instead of 
  ```
        num_dims = data.shape[1]
        n_elements = data.shape[0]
  ```
  then `n_elements, num_dims = data.shape`
  
  In addition, `pop_list` in `run_VIA` was defined but never used so was removed

**Comment by GreenGilad** [comment]
I also split the examples of all the different datasets to a separate file - this way it is easier to understand which part is the VIA algorithm and which is the examples.

There are still many lines in `run_subPARC` that have code specific for all of these examples (2610-2648, 2716-2802 and the functions that are called there fore finding the root). Maybe it is worth having classes that derive from the VIA class for these cases?

**Comment by ShobiStassen** [comment]
Thank you so very much for all your really neat contributions and modifications. I really appreciate your efforts to polish the code and make it neater. A big thank you :)

**Comment by ShobiStassen** [comment]
@GreenGilad glad to hear it is working for your problem. what kind of data set are you using Via on, if i might ask? I find the parameter for graph pruning, cluster_graph_pruning_std, and the number of visualized outgoing edges, max_visual_outgoing_edges, to be quite useful to play around with to observe different levels of complexity of the trajectories. 
there are actually lots of things I want to improve/add for Via, just been busy/distracted with other projects cropping up!

**Comment by GreenGilad** [comment]
@ShobiStassen I have sent you an email to explain a bit more about the data

**Pull request merged**
